default:
  image: cimg/node:16.14.2-browsers #lts

stages:          # List of stages for jobs, and their order of execution
  - test
  - deploy

test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - echo "Node modules modules modules..."
    - yarn install --frozen-lockfile
    - echo "Run linting..."
    - yarn lint
    - echo "Run building..."
    - yarn ui:build
    - yarn sdk:build
    - yarn react:build
    - yarn web:build
    - yarn app:build
  tags:
    - docker

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - test-deploy
  script:
    - aws --version
    - aws s3 ls
    - aws s3 sync packages/app/build s3://monite-sdk-app-dev
  tags:
    - docker
