include:
  - project: monite/infra/common-ci
    file: 'deploys.yml'

default:
  image: cimg/node:16.14.2-browsers #lts

test-job: # This job runs in the build stage, which runs first.
  stage: tests
  before_script:
    - hostname
  script:
    - yarn install --frozen-lockfile
    - echo "Run linting..."
    - yarn lint
    - echo "Run building..."
    - yarn ui-kit-react:build
    - yarn ui-kit-react:build-storybook
    - yarn sdk-api:build
    - yarn ui-widgets-react:build
    - yarn ui-widgets-react:build-storybook
    - yarn payment:build
    - yarn app-white-label:build
  tags:
    - docker
  artifacts:
    paths:
      - packages/payment/build
      - packages/ui-widgets-react/storybook_static
      - packages/ui-kit-react/storybook_static
      - packages/app-white-label/build
    expire_in: 1 day

app-white-label:
  before_script:
    - hostname
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - master
  script:
    - aws --version
    - aws s3 sync packages/app-white-label/build s3://monite-sdk-app-dev
    - aws cloudfront create-invalidation --distribution-id E2XLI83DAN4J4J --paths "/*"
  tags:
    - docker

ui-widgets-react_storybook:
  before_script:
    - hostname
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - master
  script:
    - aws --version
    - aws s3 sync packages/ui-widgets-react/storybook_static s3://monite-kit-storybook
    - aws cloudfront create-invalidation --distribution-id EHG26TRKYNPIT --paths "/*"
  tags:
    - docker

ui-kit-react_storybook:
  before_script:
    - hostname
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - master
  script:
    - aws --version
    - aws s3 sync packages/ui-kit-react/storybook_static s3://monite-ui-storybook
    - aws cloudfront create-invalidation --distribution-id E225FCWSSAPLS --paths "/*"
  tags:
    - docker
# temporary deploy to k8s cluster
#payment:
#  stage: deploy
#  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#  only:
#    - dev
#  script:
#    - aws --version
#    - aws s3 sync packages/payment/build s3://monite-payments
#    - aws cloudfront create-invalidation --distribution-id EZPL89L14KXTE --paths "/*"
#  tags:
#    - docker
