default:
  image: cimg/node:16.14.2-browsers #lts

stages: # List of stages for jobs, and their order of execution
  - test
  - deploy_app
  - deploy_payment

test-job: # This job runs in the build stage, which runs first.
  stage: test
  script:
    - echo "Node modules modules modules..."
    - yarn install --frozen-lockfile
    - echo "Run linting..."
    - yarn lint
    - echo "Run building..."
    - yarn ui:build
    - yarn sdk:build
    - yarn react:build
    - yarn web:build
    - yarn payment:build
    - yarn app:build
  tags:
    - docker
  artifacts:
    paths:
      - packages/payment/build
      - packages/app/build
    expire_in: 1 day

deploy_app:
  stage: deploy_app
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - dev
  script:
    - aws --version
    - aws s3 sync packages/app/build s3://monite-sdk-app-dev
    - aws cloudfront create-invalidation --distribution-id E2XLI83DAN4J4J --paths "/*"
  tags:
    - docker

deploy_payment:
  stage: deploy_payment
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - dev
  script:
    - aws --version
    - aws s3 sync packages/payment/build s3://monite-payments
    - aws cloudfront create-invalidation --distribution-id E25LGDILD4PO78 --paths "/*"
  tags:
    - docker
