include:
  - project: monite/infra/common-ci
    file: "deploys.yml"

default:
  image: cimg/node:16.14.2-browsers #lts

test-job: # This job runs in the build stage, which runs first.
  stage: test
  script:
    - yarn install --frozen-lockfile
    - echo "Run linting..."
    - yarn lint
    - echo "Run building..."
    - yarn ui:build
    - yarn sdk:build
    - yarn react:build
    - yarn web:build
    - yarn payment:build
    - yarn app:build
  tags:
    - docker
  artifacts:
    paths:
      - packages/payment/build
      - packages/app/build
    expire_in: 1 day

app:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - master
  script:
    - aws --version
    - aws s3 sync packages/app/build s3://monite-sdk-app-dev
    - aws cloudfront create-invalidation --distribution-id E2XLI83DAN4J4J --paths "/*"
  tags:
    - docker

# temporary deploy to k8s cluster
#payment:
#  stage: deploy
#  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#  only:
#    - dev
#  script:
#    - aws --version
#    - aws s3 sync packages/payment/build s3://monite-payments
#    - aws cloudfront create-invalidation --distribution-id EZPL89L14KXTE --paths "/*"
#  tags:
#    - docker
