# This file is used to deploy the application to Pull Preview.
# See: https://github.com/pullpreview/action/wiki/Getting-Started

name: Pull Preview Deploy
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]

jobs:
  deploy:
    environment: deploypreview # todo::unify names
    permissions:
      contents: read # to fetch code (actions/checkout)
      deployments: write # to delete deployments
      pull-requests: write # to remove labels
      statuses: write # to create commit status
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: pullpreview/action@v5
        # see https://github.com/pullpreview/action/wiki/Inputs
        with:
          admins: radist2s,nekedos
          compose_files: docker-compose.pullpreview.yml
          instance_type: small
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "eu-central-1" # Frankfurt, Zone A
